name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # (x64 or x86)
    - name: little test
      run: |
          echo "python=$(which python)"
          echo "pip=$(which pip)"
          echo "python3=$(which python3)"
          echo "pip3=$(which pip3)"
    - name: install conan
      run:  pip install --user conan
    - name: configure
      run: cmake -S . -B build/ -DCMAKE_BUILD_TYPE=Release
    - name: make (ensure we can export runtime)
      run: cmake --build build/ -j --target ExportRunTime
